import {
  useEffect,
  useState,
} from "react";

import MainLayout from "../components/MainLayout";

import {
  FileText,
  Download,
} from "lucide-react";

import {
  getInterviewSessions,
} from "../services/api";


function Reports() {

  const [
    reports,
    setReports,
  ] = useState<any[]>([]);

  const [
    loading,
    setLoading,
  ] = useState(true);


  useEffect(() => {

    fetchReports();

  }, []);


  async function fetchReports() {

    try {

      const user = JSON.parse(

        localStorage.getItem(
          "user"
        ) || "{}"
      );


      const data =

        await getInterviewSessions(
          user.id
        );


      setReports(
        Array.isArray(data)
          ? data
          : []
      );

    } catch (error) {

      console.error(error);

    } finally {

      setLoading(false);
    }
  }


  function downloadReport(
    report: any
  ) {

    const content = `

HireSense AI Interview Report

=================================

Candidate ID:
${report.user_id}

Confidence Score:
${report.confidence_score}%

Communication Score:
${report.communication_score}%

Words Per Minute:
${report.words_per_minute}

Eye Contact Score:
${report.eye_contact_score}%

Attention Status:
${report.attention_status}

=================================

AI Hiring Recommendation:

${
  report.confidence_score >= 80

    ? "Strong Candidate"

    : report.confidence_score >= 65

    ? "Potential Candidate"

    : "Needs Improvement"
}

=================================

Generated by HireSense AI
`;

    const blob = new Blob(
      [content],
      {
        type: "text/plain",
      }
    );

    const url =
      URL.createObjectURL(blob);

    const a =
      document.createElement("a");

    a.href = url;

    a.download =
      `HireSense_Report_${report.id}.txt`;

    a.click();

    URL.revokeObjectURL(url);
  }


  return (

    <MainLayout>

      <div
        className="
          max-w-7xl
          mx-auto
        "
      >

        <div
          className="
            mb-10
          "
        >

          <h1
            className="
              text-4xl
              font-black
              text-white
              mb-3
            "
          >
            AI Interview Reports
          </h1>

          <p
            className="
              text-gray-400
            "
          >
            Detailed recruiter-grade AI interview reports
          </p>

        </div>


        {loading ? (

          <div
            className="
              text-gray-400
            "
          >
            Loading reports...
          </div>

        ) : reports.length === 0 ? (

          <div
            className="
              bg-white/5
              border
              border-white/10
              rounded-3xl
              p-10
              text-center
            "
          >

            <FileText
              size={60}
              className="
                mx-auto
                text-gray-600
                mb-5
              "
            />

            <h2
              className="
                text-2xl
                font-bold
                text-white
                mb-3
              "
            >
              No Reports Found
            </h2>

            <p
              className="
                text-gray-400
              "
            >
              Complete interviews to generate reports
            </p>

          </div>

        ) : (

          <div
            className="
              grid
              lg:grid-cols-2
              gap-6
            "
          >

            {reports.map((
              report,
              index
            ) => (

              <div
                key={index}
                className="
                  bg-white/5
                  border
                  border-white/10
                  rounded-3xl
                  p-6
                "
              >

                <div
                  className="
                    flex
                    items-center
                    justify-between
                    mb-6
                  "
                >

                  <div>

                    <h2
                      className="
                        text-2xl
                        font-bold
                        text-white
                        mb-1
                      "
                    >
                      Interview Report
                    </h2>

                    <p
                      className="
                        text-gray-400
                      "
                    >
                      Candidate #{report.user_id}
                    </p>

                  </div>


                  <button
                    onClick={() =>
                      downloadReport(
                        report
                      )
                    }
                    className="
                      bg-cyan-400
                      hover:bg-cyan-300
                      text-black
                      p-3
                      rounded-2xl
                    "
                  >

                    <Download
                      size={20}
                    />

                  </button>

                </div>


                <div
                  className="
                    grid
                    grid-cols-2
                    gap-5
                    mb-6
                  "
                >

                  <div
                    className="
                      bg-black/20
                      rounded-2xl
                      p-5
                    "
                  >

                    <p
                      className="
                        text-gray-400
                        mb-2
                      "
                    >
                      Confidence
                    </p>

                    <h3
                      className="
                        text-4xl
                        font-black
                        text-cyan-400
                      "
                    >
                      {
                        report
                          .confidence_score
                      }%
                    </h3>

                  </div>


                  <div
                    className="
                      bg-black/20
                      rounded-2xl
                      p-5
                    "
                  >

                    <p
                      className="
                        text-gray-400
                        mb-2
                      "
                    >
                      Communication
                    </p>

                    <h3
                      className="
                        text-4xl
                        font-black
                        text-green-400
                      "
                    >
                      {
                        report
                          .communication_score
                      }%
                    </h3>

                  </div>


                  <div
                    className="
                      bg-black/20
                      rounded-2xl
                      p-5
                    "
                  >

                    <p
                      className="
                        text-gray-400
                        mb-2
                      "
                    >
                      WPM
                    </p>

                    <h3
                      className="
                        text-4xl
                        font-black
                        text-orange-400
                      "
                    >
                      {
                        report
                          .words_per_minute
                      }
                    </h3>

                  </div>


                  <div
                    className="
                      bg-black/20
                      rounded-2xl
                      p-5
                    "
                  >

                    <p
                      className="
                        text-gray-400
                        mb-2
                      "
                    >
                      Attention
                    </p>

                    <h3
                      className="
                        text-2xl
                        font-black
                        text-pink-400
                      "
                    >
                      {
                        report
                          .attention_status
                      }
                    </h3>

                  </div>

                </div>


                <div
                  className="
                    bg-black/20
                    rounded-2xl
                    p-5
                  "
                >

                  <h3
                    className="
                      text-xl
                      font-bold
                      mb-4
                    "
                  >
                    AI Hiring Decision
                  </h3>

                  <p
                    className="
                      text-gray-300
                      leading-8
                    "
                  >

                    {
                      report.confidence_score >= 80

                        ? `
Strong technical and communication performance.
Recommended for next-round interviews.
`

                        : report.confidence_score >= 65

                        ? `
Good foundational skills with improvement potential.
Consider additional technical screening.
`

                        : `
Candidate requires more preparation before proceeding.
`
                    }

                  </p>

                </div>

              </div>
            ))}

          </div>
        )}

      </div>

    </MainLayout>
  );
}

export default Reports;